### ISSUE TITLE
Regression for "register_extra_tool_type"

### ISSUE THREAD

**Issue by BuckarooBanzay** [ChimneySwift/multitools#4]
Looks like #2 introduced a new bug:

```
2020-08-07 06:17:06: ACTION[Main]: Server: Shutting down
2020-08-07 06:17:06: ERROR[Main]: ModError: Failed to load and run script from /var/lib/minetest/.minetest/worlds/world/worldmods/multitools/init.lua:
2020-08-07 06:17:06: ERROR[Main]: ....minetest/worlds/world/worldmods/multitools/init.lua:7: attempt to call field 'register_extra_tool_type' (a nil value)
2020-08-07 06:17:06: ERROR[Main]: stack traceback:
2020-08-07 06:17:06: ERROR[Main]: 	....minetest/worlds/world/worldmods/multitools/init.lua:7: in main chunk
```

@louisroyer (sorry to bother you :smile: )

Downstream: https://github.com/pandorabox-io/pandorabox-mods/pull/927

**Comment by rusty-snake** [comment]
The PR on the multitools repo which would add this function was closed: https://github.com/lisacvuk/minetest-toolranks/pull/11.

@BuckarooBanzay workaround for now:

```patch
 multitools = {}

-if use_toolranks then
+if false and use_toolranks then
     toolranks.register_extra_tool_type("multitool", S("multitool"))
 end
```

**Comment by BuckarooBanzay** [comment]
<img src="https://img.winfuture.de/teaser/660/30948.jpg"/>

i guess this will end up in a fork-hell... yay

**Comment by louisroyer** [comment]
I don't want to maintain a fork. I guess, I will add a feature to my [toolranks-extras](https://github.com/louisroyer/minetest-toolranks-extras) mod witch extends toolranks capabilities instead. For the moment, you can use rusty-snake's workaround (this will prints `Tool level x` instead of `Multitool level x`, but this is better than a crash) , and I will do an other PR when my API is ready. 
EDIT: The API is ready and I submitted a PR fixing this.

**Comment by programmerjake** [comment]
this isn't fixed on contentdb, can you please update this mod there?

**Comment by ChimneySwift** [comment]
Boy it's been a few years, let me know if I messed it up haha

**Comment by programmerjake** [comment]
lgtm
